export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const USER_PROFILE_ROUTE = '/user'
export const HOME_ROUTE = '/'
export const BRIGADE_ROUTE = '/brigades'
export const SCHEDULE_ROUTE = '/schedule'
export const ROOMS_ROUTE = '/rooms'
export const QUESTIONS_ROUTE = '/questions'
export const USERPROFILE_ROUTE = '/profile'

